### ISSUE TITLE
Roundup database 

### ISSUE THREAD

**Issue by omranian** [todddeluca/reciprocal_smallest_distance#5]
Dear Todd,

Sorry to spam you here. I couldn't get any email from you in google.

I’m interested to have the Roundup database to get access to the phylogenetic profiles; however, the provided website in your publication is not available:
http://roundup.hms.harvard.edu

I would appreciate it a lot if you could please share with me the Roundup database, I’m interested in A. th. ’s phylogenetic profiles.

Thanks a lot in advance.

Kind regards,
Nooshin

--
Dr. Nooshin Omranian,
Systems Biology and Mathematical Modeling Max-Planck-Institute of Molecular Plant Physiology Am Mühlenberg 1
14476 Potsdam, Germany
phone +49 (0)331 567-8548

**Comment by todddeluca** [comment]
Dear Nooshin,

Thanks for reaching out! I'm sorry to say that Roundup is a dead project
and no longer available online.

The code for the website and computation pipeline is available at
https://github.com/walllab/roundup. Theoretically, it could be run on your
local computer or computational cluster, though it would probably be a bit
of work to get it running.

The code for the underlying orthology algorithm is available in this
repository.

Here is a list of some other orthology projects that might have what you
want: https://questfororthologs.org/orthology_databases.

Please reach out if you have any questions. I'm happy to help.

Best regards,
Todd

--
Todd DeLuca
PhD Student, Complex Systems and Data Science
University of Vermont
todd.deluca@uvm.edu
